name: Build

on:
  workflow_dispatch:
    inputs:
      nodeVersion:
        description: 'Node.js version'
        required: true
        default: '20.19.0'
      ndkVersion:
        description: 'NDK version'
        required: true
        default: '27.2.12479018'
      arch:
        description: 'Arch'
        required: true
        default: 'arm64'
      sdkPlatform:
        description: 'SDK platform'
        required: true
        default: '35'

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Fetch Node.js ${{ github.event.inputs.nodeVersion }}
      run: |
        curl -OL "https://github.com/nodejs/node/archive/refs/tags/v${{ github.event.inputs.nodeVersion }}.zip"
        unzip -d . "v${{ github.event.inputs.nodeVersion }}.zip"

    - name: Patch Node.js
      working-directory: node-${{ github.event.inputs.nodeVersion }}
      run: |
        patch -p0 < ../android-configure.patch
        patch -p0 < ../zlib.patch
        cat ./android_configure.py
        cat ./deps/zlib/zlib.gyp

    - name: Configure
      working-directory: node-${{ github.event.inputs.nodeVersion }}
      env:
        CC_host: gcc
        CXX_host: g++
        AR_host: ar
      run: |
        chmod +x ./android-configure
        ./android-configure "$ANDROID_HOME/ndk/${{ github.event.inputs.ndkVersion }}" "${{ github.event.inputs.sdkPlatform }}" "${{ github.event.inputs.arch }}"

    - name: Cache Build Output
      uses: actions/cache@v4
      with:
        path: |
          node-${{ github.event.inputs.nodeVersion }}/out/Release
        key: build-${{ runner.os }}-${{ github.event.inputs.nodeVersion }}-${{ github.event.inputs.arch }}-${{ github.event.inputs.sdkPlatform }}-${{ github.event.inputs.ndkVersion }}

    - name: Build
      working-directory: node-${{ github.event.inputs.nodeVersion }}
      env:
        CC_host: gcc
        CXX_host: g++
        AR_host: ar
      run: make -j4

    - name: Distribute
      working-directory: node-${{ github.event.inputs.nodeVersion }}
      run: |
        mkdir -p ../build/lib
        mkdir -p ../build/bin
        python3 ./tools/install.py --headers-only --dest-dir ../build --prefix / install
        [[ -f ./out/Release/libnode.so ]] && cp -rpf ./out/Release/libnode.so ../build/lib/ || echo "out/Release/libnode.so does not exist"
        [[ -f ./out/Release/node ]] && cp -rpf ./out/Release/node ../build/bin/ || echo "out/Release/node does not exist"

    - uses: actions/upload-artifact@v4
      with:
        name: libnode
        path: |
          ./build
        if-no-files-found: ignore # 'warn' or 'ignore' are also available, defaults to `warn`
        retention-days: 1
